server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    #falser标水不向注册中心注册自己
    register-with-eureka: false
    #falser表示自己端就是注册中心，我的职责就是维护服务实例，并不去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/